apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: team-b-store
    kind: SecretStore
  target:
    name: my-k8s-secrets
    creationPolicy: Owner
  data:
  - secretKey: my-token
    remoteRef:
      key: argocd-gitlab-deploy-token

