apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: team-b-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-2
      # replace this role which should be managed by team-b
      role: arn:aws:iam::xxxxxxxxxxxx:role/test-secrets-role

